### ISSUE TITLE
how ddG calculated in mutatex

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/mutatex#100]
To have support to a doubt that often comes out from different people. How mutatex estimate the ddGs? it has to be intended as unfolding or folding free energy? 
And also the difference is wt-mutant or mutant-wt?

**Comment by mtiberti** [comment]
## Short answer

* differences are calculated as ΔG Mutant - ΔG Wild-type
* ΔG Mutant and ΔG Wild-type are free energies of Folding

## Long answer

### Direction of the difference

MutateX parses the FoldX output file `Dif_*`. This contains the energy differences already. It can be verified empirically, for instance:

Dif file:

```
Pdb     total energy
1IST_model0_checked_Repair_1_0.pdb      2.48292
```
Raw file (contains all the single energy values):

```
Pdb     total energy
1IST_model0_checked_Repair_1_0.pdb      -5.72708
...
WT_1IST_model0_checked_Repair_1_0.pdb   -8.20999
```
which means
```
-5.72708 - (-8.20999) =~ 2.48292
```
This is also corroborated in the FoldX fixes section (mutatex uses BuildModel):
http://foldxsuite.crg.eu/node/2897

This seems however less clear elsewhere in the documentation:
http://foldxsuite.crg.eu/command/BuildModel

```
Dif_PDB_BM.fxout -> energy difference between reference WT and the corresponding mutant
Raw_PDB_BM.fxout -> full energy decomposition for the WT references and the mutants
```

I think the content of the files is what matters most, and it seems pretty consistent to me.

### Direction of free energy

Looking at the documentation http://foldxsuite.crg.eu/command/Stability

> Calculates the DG to fold the proteins from their unfolded state.
> Output file contains the Gibbs energy of protein folding decomposed into the different terms used by FOLD-X.

From one of the original FoldX papers 

Joost Schymkowitz, Jesper Borg, Francois Stricher, Robby Nys, Frederic Rousseau, Luis Serrano, The FoldX web server: an online force field, Nucleic Acids Research, Volume 33, Issue suppl_2, 1 July 2005, Pages W382–W388, https://doi.org/10.1093/nar/gki387:

> The difference in the calculated free energies (ΔΔG) between the final state (the mutant) and the reference state (the wild-type protein) correlates well with the experimentally observed change in stability. On the other hand, the **free energy of folding** is calculated from the difference in Gibbs free energy between the detailed 3D structure found in the PDB file and a hypothetical unfolded reference state of which no structural detail is available. The main assumption in this approach is the absence of persistent structure in the denatured state, which in a range of proteins was experimentally shown to be only partly correct. Therefore, although the **free energy for folding** predicted by the FoldX force field for most small protein domains yields a number between −5.0 and −15 kcal mol −1 , this value should not be considered as absolute since it could have large error. Nevertheless, positive energies are normally indicative of problems

In fact the free energies we get with FoldX are usually negative, at least for "large" stable proteins.

## Where do we stand respect to this

Our documentation is already consistent with this:

> MutateX uses FoldX to systematically calculate the difference in free energy of folding (∆∆G) between mutated variants and the wild-type using the FoldX BuildModel command


I tried looking in the repository and couldn't find anything different. But please let me know if I have missed something
