### ISSUE TITLE
interface_ddgs 

### ISSUE THREAD

**Issue by bhavranek** [ELELAB/mutatex#101]
Hello,
I have tried running mutatex using the binding interface command. I even specified the binding interface_runfile_template.txt. However, after the job is completed and I check the results folder I only have the regular mutation_ddgs folder with the results. There are no results for the interface_ddgs. I am not sure how to proceed. This is the second time this has happened.

**Comment by mtiberti** [comment]
Hi, that is a bit strange indeed, can you please give us some more details about your calculation? At least the exact command you're using, and if something related to the interaction energies shows up in the output. Thank you!

**Comment by bhavranek** [comment]
mutatex ACE2_RBD_10ns.pdb ACE2_RBD_20ns.pdb ACE2_RBD_30ns.pdb --multiple-models -R repair_runfile_template.txt -I interface_runfile_template.txt -f suite5 --np 24 -p 24 -binding-interface --mutlist mutation_list.txt

this was my command. Is there something else I should try.

**Comment by bhavranek** [comment]
I am not sure what you mean by if something related to interaction energies shows up in the output.

**Comment by bhavranek** [comment]
I will also say when I use "--binding-interface" which is what the manual suggest it says unrecognized argument. I have to use "-binding-interface" for it to work

**Comment by bhavranek** [comment]
I would also like to ask, does it calculate the interaction energy for each individual residue with all possible mutants. Or only the interaction energy for the entire complex?

**Comment by bhavranek** [comment]
@mtiberti 
Hello, 
I have tried a number of different ways using a test pdb with 4 residues 2 in each chain A and B. No matter what I try I do not get the interface_ddgs only the mutation_ddgs folder.

**Comment by mtiberti** [comment]
it calculates the interaction energy between protein chains upon mutation (and mutations work as when just calculating folding energy - so it calculates it for every mutation). Could you please share your test PDB? I'll try and reproduce the issue

**Comment by bhavranek** [comment]
Hello, 
I believe I fixed the issue. It turns out that after specifying the input with -I <interface.txt> I had to indicate "-B" for the binding interface energy. The --binding-interface command does not work.    
This may be something helpful to include in an updated user manual.

**Comment by bhavranek** [comment]
One more question, do the negative values in the interface_ddgs calculations indicate that the amino acid change increases the interaction energy (more favorable binding) with the other chain? Picture attached below. 

[KA335_histogram.pdf](https://github.com/ELELAB/mutatex/files/5478895/KA335_histogram.pdf)

**Comment by bhavranek** [comment]
I also noticed that when I try to make a histogram with certain residues, I receive the error "ERROR: The loaded mutation data is not consistent in size. Exiting..."

**Comment by bhavranek** [comment]
I am receiving that error with a lot of the mutations.

**Comment by bhavranek** [comment]
![Screenshot from 2020-11-02 20-14-40](https://user-images.githubusercontent.com/73792295/97938863-288b4a00-1d48-11eb-913c-7f69b92253fe.png)

Here is the exact error. It is happening with a lot of the residues. Does this mean something went wrong with the calculation?

**Comment by bhavranek** [comment]
![Screenshot from 2020-11-02 20-14-46](https://user-images.githubusercontent.com/73792295/97938931-51134400-1d48-11eb-926a-f388b709f9a2.png)

Here is the exact error. Does this mean something went wrong with the calculation. It is happening on quite a bit of residues when I try to make a histogram for them?

**Comment by mtiberti** [comment]
hi, about your questions:
1) the `--binding-energy` option works in my tests - are you sure you're running the latest version in branch master?
2) yes - negative means improved interaction
3) the error you're getting comes probably from the fact that something went wrong in the calculation
4) MutateX is limited in residue compatibility by what FoldX supports (see http://foldxsuite.crg.eu/allowed-residues) . "HSD" isn't part of this set (is that a histidine tautomer?). The plotting tools expect a full set of mutations - if some of them fail you might get errors when plotting. So I recommend checking 1) if the "checked" PDB contains all the residues 2) if FoldX hasn't failed in mutating/recognizing some of the residues, you can see in the log files in each mutation directory if you're `using --foldx-log` (and also check issue #92) if all FoldX runs went fine

**Comment by bhavranek** [comment]
I reran the job using the FoldX recognized His residue. I am still receiving errors when making a histogram for some of the residues. The errors read WARNING: Selection ... no match was found; it will be skipped 
ERROR: The loaded mutation data is not consistent in Size. Exiting..

I can open the files for the mutations and see there is data there, but the histogram will not plot them.

**Comment by bhavranek** [comment]
How can I tell if I am running the latest version? I would also like to clarify that the error was not just for His residues but for other residues as well. 

The heatmap for the mutation data also seems very off. I have ran this before and the heatmap data looked like the attached.
![Screenshot from 2020-11-03 13-12-50-1](https://user-images.githubusercontent.com/73792295/98030203-4bfcd600-1dd6-11eb-8c89-0e0183182529.png)

However, the data I'm getting now is showing now is that the majority of the mutations are stabilizing. With the majority of the plot being dark blue. 
![Screenshot from 2020-11-03 13-20-15](https://user-images.githubusercontent.com/73792295/98030909-553a7280-1dd7-11eb-9826-c1f85fa51876.png)

I can send the PDB if that would be helpful, but it will not let me attach it here. I would greatly appreciate if maybe you could try running with the PDB to see if you receive the same error.

**Comment by mtiberti** [comment]
About your question, that depends on when you downloaded it. You can compare that date with the last commit in the `master` branch here on GitHub.

About your results - agreed they look weird. Sure, please feel free to send it to via e-mail (it's in the README in the repo), I'll see what I can do, it'll take me a bit of time though

**Comment by bhavranek** [comment]
Thank you. I emailed you the PDB.

**Comment by mtiberti** [comment]
@bhavranek for the record, we solved this through personal communication - it was just a plotting scale issue. I'll close this.

**Comment by jdkjsd** [comment]
@mtiberti Hi,
![Screenshot 2022-06-18 111142](https://user-images.githubusercontent.com/107276694/174444722-e10193cd-3135-4c7b-bf2f-267e57efcdba.png)

I have the same problem. Can you please tell me how to solve it? 

thanks.
