### ISSUE TITLE
Error after the repair-phase 2

### ISSUE THREAD

**Issue by deepikapareek** [ELELAB/mutatex#103]
Error;root :The following repair runs failed to complete

**Comment by elenapapaleo** [comment]
could you give a bit of more context? such as do you get any log file in the repair folder with more information?
which command line are you using?

**Comment by deepikapareek** [comment]
1. Using MacOs
2. The error is 
ERROR:root:The following repair runs failed to complete. Exiting...
ERROR:root:	repair_/Users/../3kmd_model0_checked
which I get after the repair folder is created

**Comment by mtiberti** [comment]
thanks, we will need to more details to troubleshoot your issue. I suggest you have a look at the repair folder - if you have run the pipeline with the option `-l` and you look in the directory that contains the repair run, you should find a log file with some details. Also, could you post us your command line? This part of your error:
`repair_/Users/../3kmd_model0_checked`
is a bit strange, it's possible MutateX is having troubles dealing with paths containing `..` (see issue #91)

**Comment by deepikapareek** [comment]
1. When the command executed with -l , to create log file in the repair run folder, it is blank. No log details are there.
2. The command which is executed with pdb file is :

mutatex  /Users/pareek/Desktop/Trial/3kmd.pdb -m mutation_list.txt -f suite5 -R repair_runfile_template.txt -M mutate_runfile_template.txt -I interface_runfile_template.txt -B -l

3. The error which is shown  
ERROR:root:The following repair runs failed to complete. Exiting...
ERROR:root: repair_/Users/pareek/Desktop/Trial/3kmd_model0_checked 

the path names are correct
please suggest.

**Comment by mtiberti** [comment]
maybe I see what's going on. Can you try and run the same command, but instead have the PDB and the other accessory files in the same folder you're running MutateX from? Something like

```mutatex 3kmd.pdb -m mutation_list.txt -f suite5 -R repair_runfile_template.txt -M mutate_runfile_template.txt -I interface_runfile_template.txt -B -l```

**Comment by deepikapareek** [comment]
They all in the same folder(trial).
If it was not the case, it should give the error of file not found.

(still I tried it and the same error is shown)

**Comment by deepikapareek** [comment]
please guide.

**Comment by mtiberti** [comment]
Hi again, I had another look and I think mutatex has sometimes issues when dealing with cases in which the input PDB file is not in the current working directory (which we need to fix). However if you keep all the files in the same directory and run it from the directory itself it should be working fine or at least the error in that case is due to something different. Can you confirm that you've tried the following command from a clean directory containing only the input files and nothing else?

`mutatex 3kmd.pdb -m mutation_list.txt -f suite5 -R repair_runfile_template.txt -M mutate_runfile_template.txt -l`

**Comment by mtiberti** [comment]
hi, we have merged #106 that should fix the first issue you were having. I'm closing this since I haven't received any more feedback, feel free to comment again if you have other issues
