### ISSUE TITLE
ddg2logo revision 1

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/mutatex#119]
ddg2logo currently does a logo for stabilizing mutations, we should revise it to make it more flexible to the user 
and cover the current cases:
- below a threshold  of ddg (for a example used for the stabilizing ones)
- above a threshold of ddg (for example for destabilizing mutations)
-  in a range of interest (could for example be used for the neutral mutations or specific ranges of interest)

**Comment by elenapapaleo** [comment]
it has been discussed internally that we will cover only these two cases: 
- below a threshold of ddg (for a example used for the stabilizing ones)
 - above a threshold of ddg (for example for destabilizing mutations)

**Comment by mtiberti** [comment]
done in #123
