### ISSUE TITLE
unable to run example sh file

### ISSUE THREAD

**Issue by dypp1013** [ELELAB/mutatex#121]
I have installed foldx5 in user folder and set the path as "declare -x FOLDX_BINARY="/wxy123/home/Downloads/foldx5/foldx" ". Then I delete the " -x /usr/local/foldx5/foldx " in the run.sh of example script. I run this script and it warns "ERROR:root:The specified FoldX binary (/wxy123/home/Downloads/foldx5/foldx) is not a file. Exiting..." Below is my record, so whether the Excutable file in foldx folder is the binary file for mutatex?
<pre><font color="#4E9A06"><b>wxy123@ubuntu</b></font>:<font color="#3465A4"><b>~/Downloads/mutatex</b></font>$ . mutatex-env/bin/activate
(mutatex-env) <font color="#4E9A06"><b>wxy123@ubuntu</b></font>:<font color="#3465A4"><b>~/Downloads/mutatex</b></font>$ cd workspace/
(mutatex-env) <font color="#4E9A06"><b>wxy123@ubuntu</b></font>:<font color="#3465A4"><b>~/Downloads/mutatex/workspace</b></font>$ cd P
bash: cd: P: No such file or directory
(mutatex-env) <font color="#4E9A06"><b>wxy123@ubuntu</b></font>:<font color="#3465A4"><b>~/Downloads/mutatex/workspace</b></font>$ cd PTEN/
(mutatex-env) <font color="#4E9A06"><b>wxy123@ubuntu</b></font>:<font color="#3465A4"><b>~/Downloads/mutatex/workspace/PTEN</b></font>$ sh run.sh 
INFO:root:MutateX logging started.
INFO:root:Running on Python 3.8.10, the interpreter is /home/wxy123/Downloads/mutatex/mutatex-env/bin/python
ERROR:root:The specified FoldX binary (/wxy123/home/Downloads/foldx5/foldx) is not a file. Exiting...
run.sh: 9: cd: can&apos;t cd to mutations
rm: missing operand
Try &apos;rm --help&apos; for more information.
rm: missing operand
Try &apos;rm --help&apos; for more information.
rm: missing operand
Try &apos;rm --help&apos; for more information.
rm: missing operand
Try &apos;rm --help&apos; for more information.
tar: mutations: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
</pre>

**Comment by mtiberti** [comment]
Hi,
I tried running the example following your approach and it starts fine to me. 
It looks like mutatex is having troubles finding your executable. Can you please double check if the executable is in the position you expect in the file system and is readable by you? E.g. can you just from the shell

```
declare -x FOLDX_BINARY="/wxy123/home/Downloads/foldx5/foldx
$FOLDX_BINARY
```

you should get something like:

```
$ declare -x FOLDX_BINARY="/usr/local/foldx5_2022/foldx"
$ $FOLDX_BINARY
   ********************************************
   ***                                      ***
   ***             FoldX 5 (c)              ***
   ***                                      ***
...
```

**Comment by dypp1013** [comment]
I choose to copy the whole folder into /usr/local and it runs well, thank you
