### ISSUE TITLE
Thanks for writing this code

### ISSUE THREAD

**Issue by ron-geller** [ELELAB/mutatex#125]
Just wanted to say thank you for writing this. I used to have to write a script to make the mutation file for a homo-oligomeric protein and it was a huge pain! This seems to work great and automatically finds similar chains to mutate them at the same time (and divide up the process to speed things up). It is really very useful. 
Best, 
Ron

**Comment by elenapapaleo** [comment]
Dear Ron,
Thank you so much for your positive feedback! We are extremely happy if it is useful and we are also looking forward to get any inputs on things that we could implement or modify to make it more handy.
Regards
Elena
