### ISSUE TITLE
User manual should contain more information about the format of raw data

### ISSUE THREAD

**Issue by mtiberti** [ELELAB/mutatex#130]
So that we can trace back to single calculations in cases in which for instance the standard deviation of DDG is high

**Comment by elenapapaleo** [comment]
for this I think it is better to have one of our current tool capable of interacting with the raw data and extract the DDGs of each individual run for a mutation - it can be done in my option within ddg2summary as a new option

**Comment by elenapapaleo** [comment]
I will close this issue and we open a more specific one to interact with ddg2summary
