### ISSUE TITLE
What do the mutatex usage parameters mean

### ISSUE THREAD

**Issue by fwis3** [ELELAB/mutatex#137]
Hello,
Thank you for a great program, it'll save me so much time and effort, I have an 18 subunit homo-oligomer that I've taken through FoldX. 
I'd like to give mutatex a shot but I'm not sure how to use it.
There are parameters [-h] [-a] [-u] [-B] [-C {partial, deep, none}] [-c], [-L] [-v] that are not immediately obvious to me. Do you perhaps have a resource where these are summarised.

Thank you

**Comment by elenapapaleo** [comment]
Hi! did you try to see if the manual can help to sort your doubts? 
Also if you run from the terminal mutatex -h you should have in output some description of each flag. 
manual here in this repository: https://github.com/ELELAB/mutatex/blob/master/doc/manual.pdf 
regards
Elena

**Comment by fwis3** [comment]
Hi Elena,

Thank you for responding.

One question; when I set the  pdb=$PDBS$, I get an error that a .pdb file could not be found, but when I specify the file  and it's path like a normal FoldX run, it finds it but only 1 core runs the programs instead of the 5 that has been specified. Any idea why? I see that the user guide says not to change the $PDBS$ and $NRUNS$ parameters and I understand why but it complains about not finding the file if I leave them as variables even though the .pdb file is in the same directory.

**Comment by mtiberti** [comment]
hi, @fwis3 can you please give us an example of the command line you're using? Indeed the input pdb file(s) should be only specified in the command line and the content of the `pdb` variable in the template file should not be changed under any circumstances.

the first actual calculation step of your typical mutatex run is Repair - which uses up to one core per input PDB file, so you might see the program using only one core at first if you're using a single PDB as input, and then switch to using all the assigned cores when performing the mutation runs.

**Comment by fwis3** [comment]
Hi Matteo,

mutatex myfile.pdb -np25 --foldx-binary=opt/foldx5/foldx --foldx-version suite5 --foldx-log --clean none
This one runs with an error for the BuildModel command that can't find the expected input repaired file.

mutatex myfile.pdb --np 25 --foldx-binary=/opt/foldx5/foldx --foldx-version suite5 --skip-repair --foldx-log --clean none
This one is running now, seems ok.

The second part of your message explains the single core for the repair job, thank you. The repaired .pdb file is not being saved in the folder that the BuildModel expects to find it in, in fact it's not being saved at all, I'm not sure why. So I did the repair job separately and the mutations job is running now with the correct number of cores.

**Comment by fwis3** [comment]
Hi Matteo, 

The .pdb file name had no dots in it, a re-installation of mutatex seems to have fixed the issue.
Thanks for your feedback.

The mutations job has run and ended, a bit too quickly. By my calculations it should have taken a few days but it was complete overnight. Some of the mutations files do not have any of the expected BuildModel output files. Is it correct to assume that the job didn't run completely if so why do you think that is?

**Comment by mtiberti** [comment]
Hi again,

it is possible your job didn't complete correctly. To have a more comprehensive idea of what is happening you can run `mutatex` with option `-v` (verbose mode). It's a bit difficult for me to tell what happened without seeing at least logs of the folders that didn't work and their content. You can try and rerun it using option `-v` which could give us some indications, as well as check the logs in each run's folder (if you used option `-l`).

**Comment by fwis3** [comment]
Hi Matteo,
It crashed although I'm still not sure why, there is certainly enough memory on the disk.
Anyway, I deleted the files from the previous run and started afresh, it ran successfully and completed over the weekend.

Thank you so much for creating a useful program, it saves a lot of time and effort.

**Comment by mtiberti** [comment]
Great you find it useful! You're welcome. I think we can close this issue then.
