### ISSUE TITLE
add case study for protein-DNA binding 

### ISSUE THREAD

**Issue by elenapapaleo** [ELELAB/mutatex#139]
in connection to the mode that we can use to study protein-DNA interaction, once we have verified the plotting tools work to add a case study to the user guide

**Comment by DegnKristine** [comment]
Plotting tool too be updated:  ddg2summary (with -L mutations_of_interest.txt => ERROR:root:File mutations_of_interest.txt couldn't be opened, without nothing happens). All other functions.
