### ISSUE TITLE
pdb2label seems wrongly referenced in the pdf of the manual

### ISSUE THREAD

**Issue by PaulSchrank** [ELELAB/mutatex#148]
Hello it is me again :D

Again I want to thank you for your great programm, it works great and helps me greatly in my in silico studies. I just wanted to address a little mistake in the pdf file of your manual for mutatex. There the option "pdb2labels" is wrongly called "ddg2labels" (page 12) I guess? Maybe you could correct it if possible to avoid confusion?

Best regards
Paul

**Comment by mtiberti** [comment]
hi @PaulSchrank, thank you for feedback and happy it's being useful to you!

Yes - we noticed this problem (from issue #141) and we are fixing it in and PR #146 which we should be merging soon. Thank you for your message, anyhow - I'll close this as a duplicate issue
