### ISSUE TITLE
no output from dd2g* when using a position list

### ISSUE THREAD

**Issue by aspitaleri** [ELELAB/mutatex#152]
Hi 
I am trying to run your example (i.e. Spike) in order to get heatmap/distribution:

`ddg2heatmap -p ../../wt/saturation_scan/6LZGab_noHOH.pdb -d ../../wt/saturation_scan/results/interface_ddgs/final_averages/A-B  -l ../../wt/saturation_scan/mutation_list.txt -q ../poslist_WT.txt  -b ../labels_6LZG_spike.csv -v`

`ddg2distribution -p ../../wt/saturation_scan/6LZGab_noHOH.pdb -d ../../wt/saturation_scan/results/interface_ddgs/6LZGab_noHOH_model0_checked_Repair/A-B/ -l ../../wt/saturation_scan/mutation_list.txt -q ../poslist_WT.txt -T box -s 50 -n -3 -x 16 -b ../labels_6LZG_spike.csv -v`

INFO: Residues list is:
INFO: 0	G
INFO: 1	A
INFO: 2	V
INFO: 3	L
INFO: 4	I
INFO: 5	M
INFO: 6	F
INFO: 7	W
INFO: 8	P
INFO: 9	S
INFO: 10	T
INFO: 11	C
INFO: 12	Y
INFO: 13	N
INFO: 14	Q
INFO: 15	D
INFO: 16	E
INFO: 17	K
INFO: 18	R
INFO: 19	H
/group/davila/ENVS/mutatex/lib/python3.9/site-packages/Bio/PDB/StructureBuilder.py:89: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 6414.
  warnings.warn(
/group/davila/ENVS/mutatex/lib/python3.9/site-packages/Bio/PDB/Polypeptide.py:144: BiopythonDeprecationWarning: 'three_to_one' will be deprecated in a future release of Biopython in favor of 'Bio.PDB.Polypeptide.protein_letters_3to1'.
  warnings.warn(
WARNING: Residue <Residue ZN het=H_ZN resseq=704 icode= > couldn't be recognized; it will be skipped
WARNING: Residue <Residue ZN het=H_ZN resseq=704 icode= > couldn't be recognized; it will be skipped
INFO: Positions will be read from file

Both no outputs are generated (the command is from your do.sh). I have tried to reinstall mutatex in a clean vanilla python3.9 environment.
openpyxl 3.0.10
six 1.16.0
 scipy 1.10.0
numpy==1.24.1
matplotlib==3.6.3
biopython 1.80
fonttools 4.38.0

**Comment by mtiberti** [comment]
@aspitaleri thank you - I was able to reproduce your problem. We'll investigate and be back to you ASAP - it's probably connected to some recent changes we made to the codebase

**Comment by aspitaleri** [comment]
Recently matplotlib is giving errors to my old code too - if in case it helps you.

**Comment by mtiberti** [comment]
this seems to be due to #128 - changes therein trigger an exception in the plotting scripts when using a position list, which is incorrectly handled. Working on a hotfix

**Comment by mtiberti** [comment]
@aspitaleri I haven't tested it well, but we have a hotfix in branch `fix152_no_output_with_poslist` if you're in a hurry (seems to work fine from preliminary tests)

**Comment by aspitaleri** [comment]
Hi - I pull the branch you said and it worked on your example (Spike). Thanks a lot for it.
