### ISSUE TITLE
bugs in ddg2heatmap 

### ISSUE THREAD

**Issue by aspitaleri** [ELELAB/mutatex#156]
Hi 
ddg2heatmap has a bug in saving raw matrix:

 ddg2heatmap -p all_model0_checked.pdb -l mutation_list.txt -d results_n1/mutation_ddgs/all_model0_checked_Repair -s 60 -r raw0 -o test  
Traceback (most recent call last):
  File "/group/davila/ENVS/mutatex/bin/ddg2heatmap", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2heatmap')
  File "/group/davila/ENVS/mutatex/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/group/davila/ENVS/mutatex/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/group/davila/ENVS/mutatex/lib/python3.9/site-packages/MutateX-0.8-py3.9.egg/EGG-INFO/scripts/ddg2heatmap", line 237, in <module>
TypeError: save_matrix() takes 4 positional arguments but 5 were given

indeed the function save_matrix has 4 arguments from your code - is options.raw useless in calling at line 237?

Suggestion: do you plan to add a kde density plot residues vs mutations as function of frames?  

Then, pdb2labels generates dos like csv files with $^M character. Did you notice it?

I am using this branch `fix152_no_output_with_poslist`

**Comment by mtiberti** [comment]
Hi,

thank you - we'll get on it as soon as possible.

I think the branch you're using should be the same as `master` right now as far as tools are concerned

**Comment by mtiberti** [comment]
thanks @aspitaleri, sorry it took me a while - kind of a heavy period

Looking into this

* I think we can remove `-r` from `ddg2heatmap` - basically it does the same as the `ddg2excel` tool now, which supports saving to csv file. Any reason we should keep it?
* we do KDE in `ddg2density` - maybe you want to have a look at that. It does support using datasets from single-frame runs
* for `pdb2labels` - good catch, the `csv` package we are using writes by default `dos`-format files for some reason. I'll open a different issue and we'll fix it

**Comment by aspitaleri** [comment]
Hi @mtiberti 
no problem. I used the outputs from mutatex/FoldX in a pandas dataframe for my own purpose.

-  Actually yes you can remove `-r` in my opinion. The matrix ascii is already there. I will have look to `ddg2excel` too. Thanks
-  `ddg2density` is the density on a single frame. `ddg2distribution` is probably more informative if you want to check how the DDG spreads on the all set of frames. I have generated a heatmap from the average of DDG but still it does not capture the _timeseries_ of the mutations. I have focused on a set of mutations through the frames, much easier. Thanks for the suggestions. 
- good. I noticed it opening in vim.

**Comment by mtiberti** [comment]
@aspitaleri would you mind reviewing #158 and #159 for us? It would be useful so we can close these quickly

**Comment by aspitaleri** [comment]
Sure. Clone the new version from GitHub asap. I will tell you soon

**Comment by aspitaleri** [comment]
@mtiberti  done perfectly. Thanks. When you merge on the master I will re-install it.
Best

**Comment by mtiberti** [comment]
Perfect! Thank you so much. I'll merge right away
