### ISSUE TITLE
Modifications to setup.py file 

### ISSUE THREAD

**Issue by Alvaroguleon** [ELELAB/mutatex#170]
Two modifications are to be done in the setup.py file. 
1. The package version should be specified for numpy, scipy and matplotlib. When MutateX is installed from scratch on python 3.7, the installer automatically tries to install versions of these packages which are incompatible with versions of Python lower than 3.9. This modification would avoid that problem.
2. A new package, adjustText, is now required for ddg2pca

**Comment by mtiberti** [comment]
done in #200
