### ISSUE TITLE
WARNING:root:FoldX exited with error for run repair_L8S8! Return code 5

### ISSUE THREAD

**Issue by mceminsky** [ELELAB/mutatex#173]
Hi,
I keep getting the above error at the beginning of the repair phase. Using just FoldX for RepairPDB on the same pdb file works fine. I can't tell where my problem is originating.
My inputs:
-x 
-p
-f
-R
-M
-B
-I
Thanks in advance!

**Comment by mtiberti** [comment]
hi @mceminsky ,
this usually means that FoldX fails for some reason, as you can assume.

I suggest you rerun from scratch adding option `-l` (lowercase L), that makes MutateX write a log file with the exact output it gets from FoldX inside each `repair` directory. If you look into this file, this should tell you the exact reason FoldX failed.

connected to this, have you by any chance modified the template run files?

**Comment by mceminsky** [comment]
Hi, thanks for your response! The log file ends after the following:
1 models read: pdb.pdb
Repair will take all residues into account

I have modified the template run files but they are currently unmodified from the originals.

**Comment by mtiberti** [comment]
this is a bit unusual, for a couple reasons:
  - normally, the PDB files generated by MutateX to be repaired end with `_model*_checked.pdb` so I'm not sure I understand why this isn't the case for you
  - normally, that strings you're reporting is just at the beginning of the repair in FoldX. If it crashed just right after that there might be something unusual with your PDB

it would be easier if you could share a minimal test case that reproduces your problem (can be your real case study or something else), would you be able to do that? You can also write me at my email address (I'm not sharing it here publicly, but I'm sure you can find it very easily - I'm the first author of the MutateX paper :) )

**Comment by mceminsky** [comment]
It actually does end with _model0_checked.pdb - my bad! 
I get the same error when I run the p53 example with 3kmd.pdb

WARNING:root:FoldX exited with error for run repair_3kmd_model0_checked! Return code 5
ERROR:root:The following repair runs failed to complete. Exiting...
ERROR:root:     repair_3kmd_model0_checked

And from the FoldX log:
Start RepairPDB >>>

MainChain Atoms P missing for ./3kmd_model0_checked.pdb GE1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0_checked.pdb GF1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0_checked.pdb GE1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0_checked.pdb GF1. Creating a GAP.
1 models read: 3kmd_model0_checked.pdb
Repair will take all residues into account

Thank you for the help!

**Comment by mtiberti** [comment]
@mceminsky does the repair log say anything else? E.g. for my 3kmd example I see the same as you:

```
Reading config file 'runfile.txt'
Start RepairPDB >>>

MainChain Atoms P missing for ./3kmd_model0.pdb GE1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0.pdb GF1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0.pdb GE1. Creating a GAP.
MainChain Atoms P missing for ./3kmd_model0.pdb GF1. Creating a GAP.
1 models read: 3kmd_model0.pdb
"3kmd_model0_Repair.fxout"
Repair will take all residues into account
...
```
but then I get much more output, and at the end of the repair I get:
```
End time of FoldX:
Total time spend: 4825.84 seconds.
Cleaning RepairPDB...DONE
Output PDB ./3kmd_model0_Repair.pdb
Your file run OK
```

don't you get this at all? How does your log file end?

**Comment by mceminsky** [comment]
Mine ends after "Repair will take all residues into account"

**Comment by mceminsky** [comment]
Hi @mtiberti,

It seems like the problem is actually originating in FoldX. Thank you for all your help and responses!
