### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by yongwang123222** [ELELAB/mutatex#175]
This is the contents of my run.sh：

mutatex dsm_wt.pdb \
	-p 14 \
	-m mutation_list.txt \
	-f suite5 \
	-R repair_runfile_template.txt \
	-M mutate_runfile_template.txt \
        -C partial \
	--foldx-log

When I use mutatex to perform foldx positionscan on all the amino acids in the protein sequence, I keep getting errors.
INFO:root:All positions will be considered
INFO:root:The following residue groups will be considered:
INFO:root:Running mutate runs
Traceback (most recent call last):
  File "/Users/wangyong/Desktop/wangyong_workshop/foldX/mutatex-env/bin/mutatex", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'mutatex')
  File "/Users/wangyong/Desktop/wangyong_workshop/foldX/mutatex-env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/wangyong/Desktop/wangyong_workshop/foldX/mutatex-env/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1572, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/wangyong/Desktop/wangyong_workshop/foldX/mutatex-env/lib/python3.11/site-packages/MutateX-0.8-py3.11.egg/EGG-INFO/scripts/mutatex", line 381, in <module>
IndexError: list index out of range

Due to my lack of computer knowledge, I have been looking for a solution for several days but have not been able to solve it. Is this problem caused by the environment variables I set? Or is it a software dependency compatibility issue? could you help me fix it? tthanks

**Comment by mtiberti** [comment]
hi @yongwang123222 , 

I've never seen this problem before - but in your output I see:

```
 INFO:root:The following residue groups will be considered:
```

after this text, there should be a list of the residue or residue groups that MutateX will consider, but there are none here - which I think is the source of your problem. Are there any issues with your pdb file, e.g. does it have protein residues correctly specified with `ATOM` entries? Please feel free to share it (or the whole run) with me privately and I can have a look. I'm the first author of the MutateX paper, so you can easily find my contact. I'm sure we can get to the root of this problem :)

**Comment by mtiberti** [comment]
I have investigated this - it is connected with changes in in Biopython that make versions >1.78 incompatible with MutateX. This is connected with other problems we've had - we need to refactor MutateX so that it is compatible with the latest dependency versions. Can you install Biopython 1.77 and see if that fixes your issue?

**Comment by yongwang123222** [comment]
Thank you very much for your reply. I tried running it with python version 3.11 and biopython version 1.77. Now everything is normal and all residues are recognized. The problem should be solved. It is the incompatibility between biopython>1.77 and python3.11. It is very Thank you for your patient help and guidance. It has solved the problem that has been bothering me these days. Thank you very much.
