### ISSUE TITLE
Error concerning FoldX executable file

### ISSUE THREAD

**Issue by ntlquan** [ELELAB/mutatex#180]
Hello, I am getting this error when trying to run MutateX for the entire YFP protein (5yr3.pdb). My goal is pretty simple, I'm trying to get the DDG values for all amino acid changes to the entire length of YFP. However I keep getting this error which has something to do with the FoldX executable file (foldx_20231231) not being formatted correctly. I'm not sure where to start troubleshooting, I have tested all of the available FoldX downloads on their official website for versions 4 and 5. The command I am running is:

> mutatex 5yr3.pdb -m mutation_list.txt --foldx-version=suite5 --foldx-binary=foldx_20231231 --rotabase=rotabase.txt &> mutatex.log

Any help is appreciated, thank you.
<img width="1306" alt="Screen Shot 2024-02-13 at 3 07 54 PM" src="https://github.com/ELELAB/mutatex/assets/159963013/3687f1aa-c411-408d-9aa6-d4ffaca44e3d">

**Comment by mtiberti** [comment]
Hi @ntlquan, the error you see doesn't depend on MutateX, it most likely means that you're using a FoldX executable that is not compatible with the processor architecture of the system you're using. You can verify this by running foldx without arguments, you should receive a similar error. If this is the case you should replace your FoldX installation with one that is compatible with your system

**Comment by ntlquan** [comment]
Also, I have attached a screenshot of the list from the Unrecognized_molecules.txt file that was generated. 
BF6 is the region of the internal chomophore of YFP.
<img width="262" alt="Screen Shot 2024-02-14 at 11 16 34 AM" src="https://github.com/ELELAB/mutatex/assets/159963013/5cb33d13-25bf-4d2d-bcdd-d1b618d6b0e8">

**Comment by mtiberti** [comment]
Hi @ntlquan, thanks for the update and happy you could make it work. The problem you're experiencing now is because FoldX only supports a [limited set of residues and molecules](https://foldxsuite.crg.eu/allowed-residues). If anything in a PDB doesn't belong to that list, FoldX ignores those residues and complains. This failure mode is detected by MutateX which stops accordingly. In order to make your PDB work with MutateX you need to remove all residues that are not supported by FoldX - in this case your BF6. Whether this is acceptable from a scientific standpoint very much depends on the scientific question you're trying to address. Hope this helps

**Comment by mtiberti** [comment]
You're welcome and happy to help!

This seems to be the same problem as #175 which is caused by #176. You can fix it by installing Biopython version 1.78 or lower (if you're using a Python env this would be `pip install biopython==1.78`)

**Comment by ntlquan** [comment]
Hi @mtiberti, thank you for the suggestion. I changed my biopython version to 1.78 and that fixed the issue. However now I am getting the following: 
[mutatex_yfpedited.log](https://github.com/ELELAB/mutatex/files/14288833/mutatex_yfpedited.log)
It looks like maybe FoldX itself is failing with the list of residues and when the mutatex workflow tries to check the results it does not find anything. In the output folder, it did generate new folders for each individual amino acid, and I've checked each one but I'm not sure what I should be looking for. I have also attached one of those individual aa output folders here: 
[GA4.zip](https://github.com/ELELAB/mutatex/files/14288853/GA4.zip)

**Comment by mtiberti** [comment]
@ntlquan it looks like FoldX is failing for every single run, which is unusual. Try rerunning MutateX with the `-l` (that is lowercase L) or `--foldx-log` option. This should save the output of each FoldX run into a log file called `FoldX.log` in mutation folder (so for instance, inside `mutations/pdb_name/GA4`). This should give us some clue on why FoldX is not able to perform your calculation.

**Comment by ntlquan** [comment]
Hi @mtiberti, I made the edit as you suggested and my script ran without complications! Thank you so much for all of your help.
