### ISSUE TITLE
PDB Parsing Error while using ddg2excel

### ISSUE THREAD

**Issue by PaulSchrank** [ELELAB/mutatex#182]
Dear the wonderful people from ELELAB,

while trying to run  **ddg2excel** after a finished mutatex run I get the following Error:

Matplotlib created a temporary config/cache directory at /tmp/matplotlib-gmn3dyem because the default path (/home/pschrank/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
ERROR: Position B340 was not identified in the input PDB files. Exiting...
Traceback (most recent call last):
  File "/home/pschrank/Programms/mutatex/mutatex-env/bin/ddg2excel", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2excel')
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/MutateX-0.8-py3.6.egg/EGG-INFO/scripts/ddg2excel", line 80, in <module>
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/MutateX-0.8-py3.6.egg/mutatex/utils.py", line 252, in filter_reslist
TypeError

For running **ddg2excel** I use the following command: 

ddg2excel -p RgTAL_Holo_model0_checked.pdb -d results/mutation_ddgs/final_averages/ -l mut_list_ssm.txt -q pos_list.txt -o RgTAL_active_SSM -F csv -M

(I provide all files in the Gigamove link: https://gigamove.rwth-aachen.de/de/download/a024c4cbf052ae3c9e6c110d48efb7c0)

It seem like there is a compatibility issue between my input PDB structure and the position list file, but I don't know where it stems from, it worked totally fine when carrying out the SSM run. In this case the protein is a homo-tetramer, maybe this produces the issue,  but this should be treated correctly by providing the -M option?

Do you have maybe an idea for troubleshooting?

Best regards and a pleasant weekend,

Paul

**Comment by mtiberti** [comment]
hi @PaulSchrank,

I would indeed need to look at your calculation to check - I am trying to download the zip file to check from the website you linked, but nothing happens upon clicking the Download button. I have tried with Safari, Chrome and Firefox, same result. Any suggestion?

**Comment by PaulSchrank** [comment]
Hey @mtiberti,

I apologize I don't really know why you are not able to download. Maybe because it is a File Sharer from german university? But tilll now it didn't produce any issues :( 

Anyhow here is a new link from my google drive, hopefully you can access it from there:

**Comment by PaulSchrank** [comment]
Ups sent it prematurely :D

https://drive.google.com/file/d/15TbUGl07HbWP7fw8DMj62nPynQJl0PU9/view?usp=drive_link

Thanks for your help!
Best regards
Paul

**Comment by mtiberti** [comment]
Thanks @PaulSchrank that worked! I'll ping you once I know something - probably not before Thursday

**Comment by mtiberti** [comment]
hi @PaulSchrank I just had a cursory look. A few notes:
  - strictly speaking MutateX doesn't seem to think your structure is a homotetramer, for multimer mode to work properly all sequences in the multimer must have *exactly* the same sequence which is not the case looking at the PDB. I think here MutateX just considered the four chains independently, looking at the output
 - there's something strange with your run, did it complete? Is the position list in the folder the one you actually used? I see e.g. that HB114 is in the poslist but it's not present in the results which is unexpected to me
 
Using the latest version of MutateX I get:

```
ddg2excel -p RgTAL_Holo_model0_checked.pdb -d results/mutation_ddgs/final_averages/ -l mut_list_ssm.txt -q position_list.txt -o RgTAL_active_SSM -F csv -M
WARNING: Residue <Residue NME het=H_NME resseq=42 icode= > couldn't be recognized; it will be skipped
WARNING: Residue <Residue ACE het=H_ACE resseq=42 icode= > couldn't be recognized; it will be skipped
WARNING: Residue <Residue NME het=H_NME resseq=87 icode= > couldn't be recognized; it will be skipped
...
ERROR: HB114 residue is not written in the right format or it is not contained in pdbfile
```

so no crash for me - but still unexpected output, since HB114 is in the PDB and the format looks correct. I'll investigate further when I have more time

**Comment by PaulSchrank** [comment]
Hey @mtiberti,

sorry for the late response! I apologize for the confusion, the Error was meant for the `RgTAL_active` folder and the `RgTAL` folder seemed to slip in when zipping the files! In the `RgTAL` folder I had some issues with the PDB as you mentioned (I don't really know, where they stem from, I prepared the structures with MOE and YASARA and I guess while parsing the structures during Loadup it messed with the files) so I only got a messed up results for chain A when running with mutateX. So I re-prepared the structure and only carried out the run in `RgTAL_active` using the position list for my preasumed active site residues. I tried there again with your suggested command, but still got a error:

~/Programms/mutatex/RgTAL_active> ddg2excel -p RgTAL_Holo_model0_checked.pdb -d results/mutation_ddgs/final_averages/ -l mut_list_ssm.txt -q pos_list.txt -o RgTAL_active_SSM -F csv -M
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2hbk3_y_ because the default path (/home/pschrank/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
ERROR: Position A247 was not identified in the input PDB files. Exiting...
Traceback (most recent call last):
  File "/home/pschrank/Programms/mutatex/mutatex-env/bin/ddg2excel", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'ddg2excel')
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/MutateX-0.8-py3.6.egg/EGG-INFO/scripts/ddg2excel", line 80, in <module>
  File "/home/pschrank/Programms/mutatex/mutatex-env/lib64/python3.6/site-packages/MutateX-0.8-py3.6.egg/mutatex/utils.py", line 252, in filter_reslist
TypeError

It still seems to not recognize the position list correctly and tries to find an "A247" as in Alanine instead of the "NA247" as in the Asparagin of chain A :(

Could it be that there is a problem with my biopython version, that produces these issues? I run mutateX on Python 3.6.15 and these are the packages I have installed in the environment: 

Package         Version
--------------- -------

- biopython       1.79
- cycler          0.11.0
- et-xmlfile      1.1.0
- kiwisolver      1.3.1
- matplotlib      3.3.4
- MutateX         0.8
- numpy           1.19.5
- openpyxl        3.0.10
- Pillow          8.4.0
- pip             21.3.1
- pyparsing       3.0.9
- python-dateutil 2.8.2
- scipy           1.5.4
- setuptools      44.1.1
- six             1.16.0

Thank you kindly for your help and have a pleasant day

Paul

**Comment by mtiberti** [comment]
thanks for the clarification @PaulSchrank , are you using the latest version of MutateX from the `master` branch of the repository? I suspect not since `raise TypeError` is line 262 nowadays and there's no way line 252 could trigger a `TypeError`. If not, can you try and install the latest version and see if the error persists?

**Comment by PaulSchrank** [comment]
Hey @mtiberti, I tried it with a fresh installation and it worked wonderful! Thank you very much for the help and have a nice weekend! :D

Best regards

Paul 

(P.S. the issue could be closed now!)

**Comment by mtiberti** [comment]
great to hear! Always happy when things work out ;)

and a great weekend to you
