### ISSUE TITLE
ERROR:root:couldn't read or parse your PDB file

### ISSUE THREAD

**Issue by TangJiajie0818** [ELELAB/mutatex#186]
Hello！ I‘ve encountered a little issue when running mutatex.py in pycharm.

In configuration, I've already set the parameter:
PDBFILE  "C:\Users\fang\Desktop\mutatex-master\examples\Spike\wt\saturation_scan\6LZGab_noHOH.pdb"  

It turns out error:
ERROR:root: couldn't read or parse your PDB file
ERROR:root: Couldn't load PDB structure; exiting...

So is there something wrong, please help me! Thank you!

**Comment by mtiberti** [comment]
hi @TangJiajie0818 ,
we've never tested MutateX on Windows. I think it would be simpler for you to switch to a Mac or Linux system.
Nonetheless, can you show us your full command line or script you're trying to run?

**Comment by TangJiajie0818** [comment]
I will try Linux system, thanks!

The script is the mutatex.py
 (website：https://github.com/ELELAB/mutatex/bin)

Based on the script, i add some parameters, it didn't work out.

**Comment by TangJiajie0818** [comment]
Still didn't work out. Output is as follows.
So what's the cause that i can't input my pdbfile.

These are the parameters set in configuration.
PDBFILE 
"/home/tang/Desktop/mutatex-master/examples/Spike/wt/saturation_scan/6LZGab_noHOH.pdb"  
--foldx-binary  
"/home/tang/Desktop/mutatex-master/foldx5.exe"  
--rotabase 
"/home/tang/Desktop/mutatex-master/rotabase.txt"  
--repair 
"/home/tang/Desktop/mutatex-master/templates/foldxsuite5/repair_runfile_template.txt"  
--mutate 
"/home/tang/Desktop/mutatex-master/templates/foldxsuite5/mutate_runfile_template.txt"

![捕获](https://github.com/ELELAB/mutatex/assets/122863588/3569c6a5-3d84-43de-893c-5a4d72e28dfb)

**Comment by mtiberti** [comment]
you don't need to modify any script to use mutatex - please see the user manual on this GitHub. On Linux you should be able to have the `mutatex` executable ready once you install

**Comment by TangJiajie0818** [comment]
Thanks@mtiberti，i tried Linux, it can be run now!
I've already set the env, running the tests.
Thanks a lot！

**Comment by mtiberti** [comment]
great! Just a note, please be sure to have Biopython 1.78 installed instead of newer versions because of #175

**Comment by TangJiajie0818** [comment]
Thank you for your note! 

But there is a little problem,when i'm running test：basic_multimers
It turned out :
WARNING:root: Input amino acid sequence and input position sequence is not identical in multimer.
Error:root: The supplied PDB files must have identical positiona of sequences. Exiting

It was the same error when i'm running my PDB file(it has 4 chains :A\B\C\D), and i have chacked the file.

So what could be the cause of the error?

**Comment by mtiberti** [comment]
hi @TangJiajie0818 , don't worry about the test failures - we are aware of them and are trying to address them in #184 .

About your own file, are all the chains in your PDB file identical? Could you possibly share your PDB file so we can check what's wrong?

**Comment by TangJiajie0818** [comment]
Sure,here are my PDB file and fasta sequence.
[1.zip](https://github.com/ELELAB/mutatex/files/14517395/1.zip)

**Comment by mtiberti** [comment]
hi @TangJiajie0818 , seems like we need to investigate this error further - this seems an issue with MutateX itself and probably a regression from #155

**Comment by TangJiajie0818** [comment]
OK, Thanks for your help! I will read issures in Mutatex, and try my project these days.
