### ISSUE TITLE
Error for simultaneous mutations

### ISSUE THREAD

**Issue by livmac101** [ELELAB/mutatex#188]
I am making mutations on a homodimer (6SOY), but want to make two different mutations on each chain. I am able to run mutations individually (RA109 or AB113), but when I input the combination RA109_AB113 it says it is in the wrong format. I am running python3.12 and already fixed a similar issue with reading one mutation at a time by downgrading to biopython 1.78.

**Comment by livmac101** [comment]
Just to provide more information, this is the error that I get:
ERROR:root:the position list file is not in the right format
ERROR:root:format error at RA109_AB113

I also tried making the virtualenv with python 3.9 in case that caused any issues and used biopython 1.78. Thanks!

**Comment by livmac101** [comment]
Hi @mtiberti, I'm here again! But trying out your team's other very useful tool for the same protein. Sorry for all the questions, and thanks in advance. 

[Suite5 Python3.12 Biopython1.78 RA109_AB113 double.txt](https://github.com/ELELAB/mutatex/files/14945649/Suite5.Python3.12.Biopython1.78.RA109_AB113.double.txt)
[Suite5 Python3.12 Biopython1.78 RA109 AB113 separate.txt](https://github.com/ELELAB/mutatex/files/14945650/Suite5.Python3.12.Biopython1.78.RA109.AB113.separate.txt)
[Suite5 Python3.12 Biopython1.83 RA109_AB113 double.txt](https://github.com/ELELAB/mutatex/files/14945651/Suite5.Python3.12.Biopython1.83.RA109_AB113.double.txt)
[Suite5 Python3.12 Biopython1.83 RA109 AB113 separate.txt](https://github.com/ELELAB/mutatex/files/14945652/Suite5.Python3.12.Biopython1.83.RA109.AB113.separate.txt)

Just to update more clearly for my runs on a MacOS (MacBook Air M2 2022). I have attached four files which show the commands and output from four runs:

1. Suite5 Python3.12 Biopython1.83 RA109 AB113 separate - all template files the same as in your examples, the poslist.txt is RA109 and AB113 on separate lines, the mutationlist.txt is F only. Repair and output files worked perfectly. 

2. Suite5 Python3.12 Biopython1.83 RA109_AB113 double - all template files the same as in your examples, the poslist.txt is RA109_AB113 on one line, the mutationlist.txt is F only. You can see that it didn't like the formatting for RA109_AB113. 

3. Suite5 Python3.12 Biopython1.78 RA109 AB113 separate - in case Biopython was the issue (looking at the comments here) downgraded for these. All template files the same as in your examples, the poslist.txt is RA109 and AB113 on separate lines, the mutationlist.txt is F only. Repair and output files worked perfectly. 

4. Suite5 Python3.12 Biopython1.78 RA109_AB113 double - in case Biopython was the issue (looking at the comments here) downgraded for these. All template files the same as in your examples, the poslist.txt is RA109_AB113 on one line, the mutationlist.txt is F only. You can see that it still didn't like the formatting for RA109_AB113. 

Any help would be much appreciated!

I am also wondering whether (like for RosettaDDGPrediction) I could theoretically specify more than more than two residues on the same or different (or both) chains. 

Thank you.

**Comment by mtiberti** [comment]
hi @livmac101, sorry for the delayed answer. Unfortunately you can't perform the calculation for two different mutations simultaneously using MutateX, that's why it doesn't work for you. This is because it has been designed as a high-throughput tool for single mutations only. If you want to just calculate the effect of a few (multiple) mutations, probably using plain FoldX is the easiest way forward.

**Comment by livmac101** [comment]
That makes sense, thank you for clarifying @mtiberti.

**Comment by mtiberti** [comment]
no worries! I think we can close this
