### ISSUE TITLE
Some residues are not recognized in ddg2histo, even though they are present in the structure and heatmaps / boxplots.

### ISSUE THREAD

**Issue by z0mBy91** [ELELAB/mutatex#189]
Hey!
First of all thank you very much for providing MutateX and also RosettaDDG prediction! I am using RosettaDDG prediction to refine upon my predictions from MutateX and i want to use MutateX for producing my plots etc. Unfortunately, when i am trying to use ddg2histo to output my graphs it only recognizes some residues. The residues in question are present in my heatmaps and boxplot etc. The issue is reproducible with the MutateX output for the same proteins. From a list of 18 residues, only 10 are recognized. For another protein structure containing the same residues i get histograms for 13 out of 18 residues. 

I have already installed the latest version of MutateX but this unfortionately didn't resolve the issue. If there's any files or whatever that i need to provide, please feel free to tell me :-)

Best, and thanks in Advance,
Johannes

**Comment by mtiberti** [comment]
hi @z0mBy91, thanks for your interest!

Ideally we would need to reproduce the problem to be able to look into it - would you be able to provide minimal (or not-so-minimal) example that does so, including input files and the command line you're using? If you prefer, you can send it to me via email. I'm sure you can find my address :)

**Comment by z0mBy91** [comment]
Dear @mtiberti, thank you for the very fast response. I have compiled and uploaded the results  from MutateX / RosettaDDG --> MutateXcompatible for both my Proteins with a short description of the commands that were used.

You can find the compiled Data at https://cloud.uni-halle.de/s/THLxEG7DkLHaxtJ.

**Comment by mtiberti** [comment]
hi @z0mBy91 , sorry for the late reply - I have just back from holidays.

Thanks for the data, I can confirm this is a bug in the script. I'll fix it as soon as I manage

**Comment by mtiberti** [comment]
I've opened #192 which contains a fix to this problem, @z0mBy91 let me know if you want to give it a test before we merge

**Comment by elenapapaleo** [comment]
since there is no answer here we need to assign an internal reviewer

**Comment by z0mBy91** [comment]
Sorry! apparently i did not receive the notification from the last post :( yes i would like to test the new pull request! it is probably #192 ?

**Comment by mtiberti** [comment]
yes - we tested it internally and merged. Still welcome to give it a test @z0mBy91 and thank you for your help :)
