### ISSUE TITLE
WARNING:root:Residue couldn't be recognized

### ISSUE THREAD

**Issue by gboyle2** [ELELAB/mutatex#190]
I'm running into this error with two different apo CYP molecules. I repaired the PDBs from crystal structures successfully, but now it cycles through every residue and says:

```WARNING:root:Residue <Residue VAL het=  resseq=490 icode= > in file /repair/repair_1og2_noheme_model0_checked/1og2_noheme_model0_checked_Repair.pdb couldn't be recognized; it will be skipped```

Here is the final traceback: 

```Traceback (most recent call last):
  File "/net/gs/vol3/software/modules-sw-python/3.12.1/mutatex/0.8/Linux/Ubuntu22.04/x86_64/bin/mutatex", line 4, in <module>
    __import__('pkg_resources').run_script('MutateX==0.8', 'mutatex')
  File "/net/gs/vol3/software/modules-sw/python/3.12.1/Linux/Ubuntu22.04/x86_64/lib/python3.12/site-packages/pkg_resources/__init__.py", line 691, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/net/gs/vol3/software/modules-sw/python/3.12.1/Linux/Ubuntu22.04/x86_64/lib/python3.12/site-packages/pkg_resources/__init__.py", line 1541, in run_script
    exec(script_code, namespace, namespace)
  File "/net/gs/vol3/software/modules-sw-python/3.12.1/mutatex/0.8/Linux/Ubuntu22.04/x86_64/lib/python3.12/site-packages/MutateX-0.8-py3.12.egg/EGG-INFO/scripts/mutatex", line 428, in <module>
IndexError: list index out of range
```

**Comment by mtiberti** [comment]
Hi @gboyle2,

this is weird - could you possible share with us the PDB you're using together with your command line and any change you made to the standard templates, so we can try and reproduce the error?

**Comment by gboyle2** [comment]
Sure thing! I uploaded the PDB files as text files because github got angry at me for trying to upload PDBs. Let me know if you would them shared another way.

[4gqs_noheme.txt](https://github.com/user-attachments/files/15841366/4gqs_noheme.txt)

[1og2_noheme.txt](https://github.com/user-attachments/files/15841364/1og2_noheme.txt)

I ran this command line:

```mutatex 4gqs_noheme.pdb --np 4 --nruns 5 -m mutation_list.txt -x ~/foldx/foldx -c -l```

The only change I made to the standard templates was changing `complexWithDNA=true` to `false` since my protein doesn't complex with DNA. Although I'm realizing that I made that change in `repair_runfile_template.txt` but not `mutate_runfile_template.txt`. Trying again, though, that inconsistency between the files doesn't seem to be the issue. I got the same error.

For what it's worth, running FoldX manually with an individual_list.txt containing all of the individual amino acid variants on these PDBs works

**Comment by bymgood** [comment]
I got the same problem I think. The protein is successfully checked and repaired with mutatex. But for the protein_checked_Repair.pdb, It reports iteratively in the terminal that every residue in this file could not be recognized; it will be skipped. 

If I am using Foldx BuildModel function directly,  I am able to run it and receive the outcome. 

**_The protein I am using is 3kmd.pdb in the p53 example folder._** 
Error messages like the below for every residue positions-
```
WARNING:root:Residue <Residue LEU het=  resseq=289 icode= > in file /Users/mutatex-master/repair/repair_3kmd_model0_checked/3kmd_model0_checked_Repair.pdb couldn't be recognized; it will be skipped
WARNING:root:Residue <Residue ARG het=  resseq=290 icode= > in file /Users/mutatex-master/repair/repair_3kmd_model0_checked/3kmd_model0_checked_Repair.pdb couldn't be recognized; it will be skipped
WARNING:root:Residue <Residue LYS het=  resseq=291 icode= > in file /Users/mutatex-master/repair/repair_3kmd_model0_checked/3kmd_model0_checked_Repair.pdb couldn't be recognized; it will be skipped
```

The command I used is -
`(base) user@MacBook-Pro-M3 mutatex-master % mutatex ./examples/p53/3kmd.pdb -x /Users/foldxMacC11_0/foldx_20241231 -b /Users/foldxMacC11_0/rotabase.txt -p 6`

**Comment by alineoa** [comment]
I am having the exact same issue while trying to run the examples provided along with MUTATEX. @bymgood could you share how you implemented the BuildModel function directly to get the outcome?

**Comment by bymgood** [comment]
@alineoa 
https://foldxsuite.crg.eu/command/BuildModel
We can follow the manual provided by the FoldX to do the calculation in a manually order. I am not sure if the issue we experienced is caused by the updated version of the FoldX. Mutatex used to work perfectly with previous versions of the FoldX though...
