### ISSUE TITLE
Limiting mutations to a list of residues

### ISSUE THREAD

**Issue by mdpoleto** [ELELAB/mutatex#89]
It would be interesting if MutateX could allow the user to limit mutations/analyses to a list of residues instead of computing for entire proteins, allowing users to save computational time. A simple *txt file (such as exemplified below) could work.

(Chain+ResID)
A27
A38
B13
B43
...

**Comment by mtiberti** [comment]
thanks for your feedback!
For the analysis scripts this can be done already - just use a PDB with only the residues you need information about. I agree it could be useful for the calculation itself if you're only interested in a part of the protein

**Comment by elenapapaleo** [comment]
we will implement this soon and be back here when available

**Comment by mtiberti** [comment]
hi @mdpoleto , I finally came around to implement this. Details are in the docs, but briefly now MutateX support option `-q` to perform the scan on a limited subset of residues
