### ISSUE TITLE
PDB files with multiple dots in the filename are not handled correctly

### ISSUE THREAD

**Issue by SimoneScrima** [ELELAB/mutatex#91]
In filenames with double dots as the outputs from Modeller ( i.e "XXX.B000001.pdb" ) FoldX truncate the filenames at the first dot after the repair run and Mutatex can't find the correct file for the next steps

**Comment by mtiberti** [comment]
Thanks! What we need to do here is probably just change the file name at check (i.e. replace dots in the filenames with underscores, for instance)

**Comment by elenapapaleo** [comment]
yes this is something we need to clarify in the documentation
