### ISSUE TITLE
Unrecognised residues from FoldX

### ISSUE THREAD

**Issue by juansv** [ELELAB/mutatex#92]
There are some residues names that cannot be recognized by [FoldX](http://foldxsuite.crg.eu/allowed-residues) (i.e protonated Histidines, residues involved in the N or C terminal).
It would be nice if Mutatex could recognize (as already does by putting on Unrecognized_Residues.txt) before running to change it manually or if Mutatex could do the analysis by recognizing and changing  it would be a nice feature.

**Comment by mtiberti** [comment]
Thanks!
Agreed - mutatex should handle those cases. I don't think mutatex should changes the residue names that are in the PDB as it could be error-prone (say, you have a HID in your PDB which is actually not histidine). However mutatex could recognise when `Unrecognized_Residues.txt` is produced and stop the calculation or warn the user.

**Comment by elenapapaleo** [comment]
Solved with PR#135
