### ISSUE TITLE
Mutation runs are getting terminated before completing

### ISSUE THREAD

**Issue by asirajeee** [ELELAB/mutatex#95]
I am getting the following error for every residue while running mutatex.

INFO:root:starting FoldX run VA227 
INFO:root:now running: VA227 
INFO:root:command is /home/salman/foldx -f runfile.txt
INFO:root:run VA227 was terminated before completing

And such error is showing for all the residues.

**Comment by mtiberti** [comment]
this could be an issue related to FoldX rather than MutateX. You can try asking MutateX to save the log file of each FoldX run and see what you get (option `-l`) to troubleshoot. Please let me know what you find

**Comment by deepikapareek** [comment]
did the above issue resolved?

**Comment by elenapapaleo** [comment]
we didn't get an answer after the test that @mtiberti suggested so it is not solved
